pip: use pkgs.fetchurl instead of builtins.fetchurl
This resolves
error: store path 'nypj2b7h41zsrmyfsiww97zb6va445gn-torch-2.0.1%2Bcpu-cp310-cp310-linux_x86_64.whl' contains illegal character '%'